### ISSUE TITLE
Error: on running the app

### ISSUE THREAD

**Issue by paliwalgaurav** [bodiddlie/rxheroes#4]
when I am trying to run the app using `npm start`, it's throwing following error:

`webpack: Compiled successfully.
[1] [default] Checking started in a separate process...
[1] ./rxheroes/node_modules/typescript/lib/typescript.js:3329
[1]                 throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
[1]                 ^
[1]
[1] Error: Debug Failure. False expression: File  has unknown extension.
[1]     at Object.assert (./rxheroes/node_modules/typescript/lib/typescript.js:3329:23)
[1]     at Object.fail (./rxheroes/node_modules/typescript/lib/typescript.js:3334:19)
[1]     at Object.extensionFromPath (./rxheroes/node_modules/typescript/lib/typescript.js:3476:15)
[1]     at ./rxheroes/node_modules/typescript/lib/typescript.js:66996:46
[1]     at Array.map (native)
[1]     at resolveModuleNamesWorker (./rxheroes/node_modules/typescript/lib/typescript.js:66990:141)
[1]     at resolveModuleNamesReusingOldState (./rxheroes/node_modules/typescript/lib/typescript.js:67117:24)
[1]     at processImportedModules (./rxheroes/node_modules/typescript/lib/typescript.js:68027:35)
[1]     at findSourceFile (./rxheroes/node_modules/typescript/lib/typescript.js:67937:17)
[1]     at processImportedModules (./rxheroes/node_modules/typescript/lib/typescript.js:68056:25)
`

**Comment by bodiddlie** [comment]
This project has gotten pretty out of date, unfortunately. My guess is this is the first of a string of issues in trying to get it to run anymore. I'll try to see if I can get it running, but I've long since switched from Angular to React. This project is probably only semi-useful as a code reference for the ngrx stuff, and not the Angular pieces anymore. 

Thanks for filing the issue though.

**Comment by paliwalgaurav** [comment]
Okay @bodiddlie, No problem. But can you please approximately tell me what should be the issue? So that I can also try to fix it.

**Comment by hungrybear88** [comment]
hey @paliwalgaurav  got this to work but its pretty messy getting all the parts to play nice 

that error above is around the awesome type loader version

**Comment by paliwalgaurav** [comment]
No problem @hungrybear88

**Comment by hungrybear88** [comment]
@paliwalgaurav  I have pushed an update under here
https://github.com/hungrybear88/rxheroes
